"""empty message

Revision ID: a2361493c6b6
Revises: c83c9513d17b
Create Date: 2022-12-26 18:53:44.965667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2361493c6b6'
down_revision = 'c83c9513d17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ChoicePercent', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('ChoicePercent')

    # ### end Alembic commands ###
