"""empty message

Revision ID: c83c9513d17b
Revises: 093693fffeb7
Create Date: 2022-12-20 18:43:16.462946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c9513d17b'
down_revision = '093693fffeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
